### ISSUE TITLE
这个和 webpack-hmr有什么差别呢

### ISSUE THREAD

**Issue by HengCC** [dora-js/dora-plugin-hmr#10]
特意花了点时间看了下 webpack 的 hot reload. 有2个实现方式

- 配置 webpack.config.js ,增加相关的 reload 配置
-  通过webpack-dev-server --hot 

我能问下 webpack-hmr 和上面的 以及 hmr 这个 plugin 有什么差异呢? 

尝试了下 user_board那个例子. 用的是 webpack-hmr 热加载会自动刷新页面. 而之前我配置的都不会刷新页面. 

目前相对比较普及和性能比较好的是哪种呢? 恳请解惑.谢谢

**Comment by sorrycc** [comment]
hmr 是基于 babel-preset-react-hmre，webpack-hmr 用原生的 webpack hmr 。

**Comment by HengCC** [comment]
两个有什么差异性呢? 哪个性能会更好点.

**Comment by sorrycc** [comment]
用途不用，babel-preset-react-hmre 会保留 react component 内部的 state，而如果用 redux 或者 dva 做开发，state 在 redux 里，不需要保留 react component 的 state，也就用不上 babel-preset-react-hmre 了。
